config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('authen.urls')),
    path('', include('diary.urls', namespace='diary')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from diary.apps import PsdiaConfig
from diary.views import RecordListView, RecordDetailView, RecordCreateView, RecordDeleteView, RecordUpdateView

app_name = PsdiaConfig.name

urlpatterns = [
    path('', RecordListView.as_view(), name="list"),
    path('detail/<int:pk>', RecordDetailView.as_view(), name="detail"),
    path('create/', RecordCreateView.as_view(), name="create"),
    path('delete/<int:pk>', RecordDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>', RecordUpdateView.as_view(), name='edit'),
]

diary/models.py
from django.db import models

from authen.models import User
from libs.truncate_table_mixin import TruncateTableMixin


class Record(TruncateTableMixin, models.Model):
    owner = models.ForeignKey(
        to=User,
        verbose_name="Автор",
        on_delete=models.CASCADE,
        related_name='records',
    )
    content = models.TextField(verbose_name="Содержание")
    created_at = models.DateTimeField(verbose_name="Создан", auto_now_add=True)

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        ordering = ('-created_at',)

    def __str__(self):
        return self.content

diary/forms.py
from django.forms import ModelForm
from diary.models import Record


class RecordForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # стилизация полей
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control text-secondary fs-4'
            field.widget.attrs['placeholder'] = "Напишите, о чем вы думаете"

    class Meta:
        model = Record
        fields = ('content',)

diary/views.py
from datetime import datetime, timedelta

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView

from diary.forms import RecordForm
from diary.models import Record
from diary.services import get_cache_key_from_request
from libs.login_required_mixin import CustomLoginRequiredMixin
from libs.managed_cache import ManagedCache
from libs.object_permission_mixin import UpdateDeleteObjectPermissionMixin, DetailObjectPermissionMixin, \
    ListObjectPermissionMixin

month_name_list = [
    '', 'января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября',
    'декабря'
]


# LIST
class RecordListView(ListObjectPermissionMixin, ListView):
    extra_context = {
        'header': 'Список записей',
        'css_list': ['record_list.css'],
    }

    model = Record
    template_name = "record_list.html"
    paginate_by = 18

    def get_queryset(self):
        # Показ своих записей с поиском

        authuser = self.request.user
        # кеширование
        cache_key = get_cache_key_from_request(self.request)
        cached_queryset = ManagedCache.get(cache_key)
        if cached_queryset:
            queryset = cached_queryset
        else:
            queryset = super().get_queryset()
            ManagedCache.write(cache_key, queryset)

        if 'search_date' in self.request.GET and 'search_phrase' in self.request.GET and self.request.GET[
            'search_date'] != '' and \
                self.request.GET['search_phrase'] != '':
            "по дате и фразе"

            created_at_interval_from = datetime.strptime(self.request.GET['search_date'], "%Y-%m-%d").date()
            created_at_interval_to = created_at_interval_from + timedelta(hours=24)
            queryset = queryset.filter(
                content__contains=self.request.GET['search_phrase'],
                created_at__gt=created_at_interval_from,
                created_at__lt=created_at_interval_to
            )
        elif 'search_date' in self.request.GET and self.request.GET['search_date'] != '':
            "по дате"

            created_at_interval_from = datetime.strptime(self.request.GET['search_date'], "%Y-%m-%d").date()
            created_at_interval_to = created_at_interval_from + timedelta(hours=24)
            queryset = queryset.filter(
                created_at__gt=created_at_interval_from,
                created_at__lt=created_at_interval_to
            )
        elif 'search_phrase' in self.request.GET and self.request.GET['search_phrase'] != '':
            "по фразе"

            queryset = queryset.filter(content__contains=self.request.GET['search_phrase'])

        return queryset if authuser.is_superuser else queryset.filter(owner=authuser)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # поля поиска записей
        if 'search_date' in self.request.GET:
            context['search_date'] = self.request.GET['search_date']
            context['search_phrase'] = self.request.GET['search_phrase']

        # урезание размера содержания
        for obj in context["object_list"]:
            obj.content = obj.content.replace("\n", "<br>")
            if len(obj.content) > 100:
                obj.content = obj.content[:100] + '..'

        return context


# CREATE
class RecordCreateView(CustomLoginRequiredMixin, CreateView):
    title = "добавить запись"
    extra_context = {
        'title': title,
        'header': title.capitalize(),
    }

    model = Record
    form_class = RecordForm
    template_name = "record_form.html"

    def form_valid(self, form):
        if form.is_valid():
            content = form.__dict__['data']['content']
            owner = self.request.user
            self.object = Record.objects.create(owner=owner, content=content)

            # удаление кэша пользователя
            cache_key = get_cache_key_from_request(self.request)
            ManagedCache.remove(cache_key)

            return redirect(self.get_success_url())
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("diary:detail", kwargs={"pk": self.object.pk})


# DETAIL
class RecordDetailView(CustomLoginRequiredMixin, DetailObjectPermissionMixin, DetailView):
    model = Record
    template_name = "record_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'].content = context['object'].content.replace('\n', '<br>')

        created_at_obj = context['object'].created_at
        created_at_hour = created_at_obj.hour if created_at_obj.hour > 9 else '0' + str(created_at_obj.hour)
        created_at_minute = created_at_obj.minute if created_at_obj.minute > 9 else '0' + str(created_at_obj.minute)
        created_at = f"{created_at_obj.day} {month_name_list[created_at_obj.month]} {created_at_obj.year}г. {created_at_hour}:{created_at_minute}"
        context['title'] = created_at
        context['header'] = "Запись от " + created_at
        return context


# UPDATE
class RecordUpdateView(CustomLoginRequiredMixin, UpdateDeleteObjectPermissionMixin, UpdateView):
    title = "обновить запись"
    extra_context = {
        'title': title,
        'header': title.capitalize()
    }

    model = Record
    form_class = RecordForm
    template_name = 'record_form.html'

    def form_valid(self, form):
        # удаление кэша пользователя
        cache_key = get_cache_key_from_request(self.request)
        ManagedCache.remove(cache_key)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("diary:detail", kwargs={"pk": self.object.pk})


# DELETE
class RecordDeleteView(CustomLoginRequiredMixin, UpdateDeleteObjectPermissionMixin, DeleteView):
    title = 'удалить запись'
    extra_context = {
        'title': title,
        'header': title.capitalize(),
    }

    def form_valid(self, form):
        # удаление кэша пользователя
        cache_key = get_cache_key_from_request(self.request)
        ManagedCache.remove(cache_key)

        return super().form_valid(form)

    model = Record
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('diary:list')

diary/templates/basic.html
<!doctype html>
{% load custom_tags %}
{% load static %}

<html lang="en" class="bgcolor-beige">
    {% include 'components/head.html' %}
    <body class="bgcolor-beige">
        <div class="d-flex justify-content-between p-3 px-md-4 mb-3 shadow-theme bgcolor-dark-beige">
            {% include 'components/header-logo.html' %}

            <div class="d-flex align-items-center">
                {% if user.is_authenticated %}
                    <img src="{{user.avatar.name|full_image_path}}" class="user-avatar me-2">
                    <a href="{% url 'authen:profile' %}" class="d-flex align-items-center me-2 fw-bolder link-success"> {{user}}</a>
                {% endif %}
                <nav>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %} <a class="btn-theme p-2" href="/admin">Админка</a> {% endif %}
                        <form action="{% url 'authen:logout' %}" method="post" class="d-inline-block">
                            {% csrf_token %}
                            <button class="btn-theme p-2 border-0">Выйти</button>
                        </form>
                    {% else %}
                        <a class="btn-theme p-2" href="{% url 'authen:login' %}">Войти</a>
                        <a class="btn-theme p-2" href="{% url 'authen:register' %}">Регистрация</a>
                    {% endif %}
                </nav>
            </div>
        </div>

        <div class="container">
            <main>
                {% include 'components/header.html' %}
                {% block content %} {% endblock %}
            </main>

        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

diary/templates/confirm_delete.html
{% extends 'basic.html' %}

{% block content %}
    <div class="pricing-header px-3 mx-auto text-center">
        <div class="w-75 mx-auto">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p class="fs-4 p-2">Действительно хотите удалить запись?</p>
                        <button type="submit" class="btn-theme w-50 border-0 mb-2">Подтвердить</button>
                        <a href="{% url 'diary:detail' object.pk %}" class=" btn-theme w-50">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

diary/templates/index.html
{% extends 'basic.html' %}
{% load custom_tags %}

{% block content %}
    <h3 class="text-center fw-bolder color-jade p-3">Приложение личного дневника</h3>
    <p class="text-center rounded shadow color-khaki bgcolor-dark-beige p-3 fs-4 w-75 mx-auto">
        Здесь вы можете хранить личные заметки, к которым только вы имеете доступ. Имеется возможность искать заметки по дате или содержанию
    </p>
{% endblock %}

diary/templates/list.html
{% extends 'basic.html' %}

{% block content %}
    <div class="d-flex justify-content-center d-flex flex-wrap rounded shadow">
        {% for obj in object_list%}
        <div class="card d-flex justify-content-between flex-column bg-light p-2 m-2 w-30">
            <div class='card-body'>
                <div class="card-title fw-bolder color-beige-gray">{{obj.created_at}}</div>
                {% if user.is_superuser %}<div class="color-jade pb-2">{{obj.owner}}</div>{% endif %}
                <p class="card-text color-beige-gray">{{obj.content}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

diary/templates/record_detail.html
{% extends 'basic.html' %}
{% load custom_tags %}

{% block content %}
    <div class="pt-2 pb-3">
        <a href="{% url 'diary:edit' object.pk %}" class="btn-theme p-1 w-25">Изменить</a>
        <a href="{% url 'diary:delete' object.pk %}" class="btn-theme p-1 w-25">Удалить</a>
    </div>
    <div class="text-center color-khaki bg-light border p-2 rounded fs-4">
        <p class="py-4 text-wrap">{{object|safe}}</p>
    </div>
{% endblock %}

diary/templates/record_form.html
{% extends 'basic.html' %}

{% block content %}
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="w-75 mx-auto">
            <form method="post" enctype="multipart/form-data" class="form-floating">
                {% csrf_token %}

                {% for field in form%}
                <p>{{field}}</p>
                {% endfor %}

                 <button type="submit" class="btn-theme border-0 rounded">Отправить</button>
                {% if header == 'Добавить запись' %}
                    <a href="{% url 'diary:list' %}" class="btn-theme btn-my-link rounded">Отмена</a>
                {% else %}
                    <a href="{% url 'diary:detail' object.pk %}" class="btn-theme btn-my-link rounded">Отмена</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

diary/templates/record_list.html
{% extends 'basic.html' %}
{% load custom_tags %}

{% block content %}
    <div class="d-flex align-items-center justify-content-between w-100">
        <a href="{% url 'diary:create' %}" class="d-block btn-theme p-2 mb-4 w-25">Новая запись</a>
        <!--поиск-->
        <form action="{% url 'diary:list' %}" method="GET" enctype="multipart/form-data" class="d-block mb-4 w-50">
            <div class="input-group rounded">
              <input type="date" name="search_date" class="color-beige-gray border rounded me-1 p-2" title="дата записи" {% if search_date %}value="{{search_date}}"{% endif %}>
              <input type="search" name="search_phrase" class="form-control rounded py-2 me-1" placeholder="Поиск записи" aria-label="Search" aria-describedby="search-addon" {% if search_phrase %}value="{{search_phrase}}"{% endif %}/>
              <button class="bgcolor-jade color-beige border-0 rounded px-2" title="Поиск">&#128269;</button>
            </div>
        </form>
    </div>

    <div class="d-flex flex-wrap justify-content-center rounded shadow bgcolor-dark-beige">
        {% for obj in object_list%}
            <a href="{% url 'diary:detail' obj.pk %}" class="record-card p-2 m-2 w-30">
                <div class='card-body'>
                    <div class="fw-bolder color-beige-gray">{{obj.created_at}}</div>
                    {% if user.is_superuser %}<div class="color-jade pb-2">{{obj.owner}}</div>{% endif %}
                    <p class="card-text color-beige-gray">{{obj.content|safe}}</p>
                </div>
            </a>
        {% endfor %}
    </div>

    <!--пагинация-->
    {% if page_obj.paginator.num_pages > 1 %}
        <div class="pagination w-75 pt-4">
            <span class="step-links fs-5">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="text-decoration-none color-beige-gray">1</a>
                    {% if page_obj.paginator.num_pages > 2 %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="text-decoration-none color-beige-gray" title="предыдущая страница"> .. </a>
                    {% endif %}
                {% endif %}

                <span class="current fw-bolder">
                    {{ page_obj.number }}
                </span>

                {% if page_obj.has_next %}
                    {% if page_obj.paginator.num_pages > 2 %}
                        <a href="?page={{ page_obj.next_page_number }}" class="text-decoration-none color-beige-gray" title="следующая страница"> .. </a>
                    {% endif %}
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="text-decoration-none color-beige-gray">
                        {{page_obj.paginator.num_pages}}
                    </a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}